let songs = [
  "Katy Perry - Dark Horse",
  "Maroon 5 - Sugar",
  "SF337-01 - Saturdays - Not Giving Up",
  "SF337-02 - Kylie Minogue - Into The Blue",
  "SF337-03 - Robbie Williams - Shine My Shoes",
  "SF337-04 - Idina Menzel - Let It Go",
  "SF337-05 - One Direction - Midnight Memories",
  "SF337-06 - Zedd Ft Hayley Williams - Stay The Night",
  "SF337-07 - Vance Joy - Riptide",
  "SF337-08 - Bastille - Flaws",
  "SF337-09 - Tinie Tempah Ft Labrinth - Lover Not A Fighter",
  "SF337-10 - Sophie Ellis Bextor - Young Blood",
  "SF337-11 - Britney Spears Ft Will.I.Am - It Should Be Easy",
  "SF337-12 - Enrique Iglesias - I'm A Freak",
  "SF337-13 - Gorgon City - Ready For Your Love",
  "SF337-14 - Ellie Goulding - Goodness Gracious",
  "SF337-15 - Wilkinson Ft Detour City - Too Close",
  "SF337-16 - Elyar Fox - Do It All Over Again",
  "SF337-17 - Macklemore & Ryan Lewis Ft Schoolboy Q & Hollis - White Walls",
  "SF337-18 - Boyzone - Light Up The Night",
  "SF359-09 - One Direction - History",
  "SF359-12 - The Corrs - Bring on the Night",
  "SF359-13 - Demi Lovato - Confident",
  "SF359-15 - Selena Gomez - Same Old Love",
  "SF361-15 - Taylor Swift - Out of the Woods",
  "SF361-16 - Gwen Stefani - Used to Love You",
  "SF361-18 - Shakira - Try Everything",
  "Shakira Ft. Rihanna - Cant Remember To Forget You",
];

export default songs;
