export const CURRENT_SWIPE_HANDLE = "CURRENT_SWIPE_HANDLE";
export const CURRENT_USER = "CURRENT_USER";
export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const SET_PROFILE = "SET_PROFILE";
