export const CURRENT_SWIPE_HANDLE = "CURRENT_SWIPE_HANDLE";
export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const SET_PROFILE = "SET_PROFILE";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_CARDS = "SET_CARDS";
