export const SWIPED_CARD_HANDLE = "SWIPED_CARD_HANDLE";
export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const SET_PROFILE = "SET_PROFILE";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_CARDS = "SET_CARDS";
export const SWIPE_PROFILE = "SWIPE_PROFILE";
